// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcfUcl4hhqTqw6NARmNIn3IqZt-PjWUbk',
    appId: '1:791263693650:web:41b50c6fa41cfb0802488b',
    messagingSenderId: '791263693650',
    projectId: 'socialmediaclone-b6db1',
    authDomain: 'socialmediaclone-b6db1.firebaseapp.com',
    storageBucket: 'socialmediaclone-b6db1.firebasestorage.app',
    measurementId: 'G-FLXCB82DRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEpluoL4vMeO8YrjKwozyCbZ3Rmkf6Qjc',
    appId: '1:791263693650:android:d548ac1413800d1f02488b',
    messagingSenderId: '791263693650',
    projectId: 'socialmediaclone-b6db1',
    storageBucket: 'socialmediaclone-b6db1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbbKpYWdnCfmKo0LI2RC8pX3ZzO25_GZc',
    appId: '1:791263693650:ios:1971b5ec7eae88bd02488b',
    messagingSenderId: '791263693650',
    projectId: 'socialmediaclone-b6db1',
    storageBucket: 'socialmediaclone-b6db1.firebasestorage.app',
    iosBundleId: 'com.socialmediaclone.socialMediaClone',
  );
}
